### ISSUE TITLE
Make deleting packages associated with a publisher less tedious

### ISSUE THREAD

**Issue by shreyabasu** [pwyf/aid-transparency-tracker#376]
Currently, packages need to be deleted one at a time from the manage organisation page (http://tracker.publishwhatyoufund.org/publish/organisations/AU-5/edit/)

**Comment by andylolz** [comment]
This continues to be tedious, but also continues to be tricky to do a better way :(

**Comment by andylolz** [comment]
Fixed as part of 3f7a67456795766812b56c6c2259bfa27d9c4f24.
