### ISSUE TITLE
Sampling driver should create a db per organisation then combine

### ISSUE THREAD

**Issue by markbrough** [pwyf/aid-transparency-tracker#448]
... to avoid the case of one error breaking everything.
https://github.com/pwyf/IATI-Data-Quality/blob/master/sample_work/driver

Wonder if it is also possible to speed it up somehow?

**Comment by andylolz** [comment]
This doesn’t happen… but also, it doesn’t error. And also, samples generate quite quickly (it takes a couple of minutes to generate all samples).
