### ISSUE TITLE
../publication_index.csv produces an internal server error

### ISSUE THREAD

**Issue by siwhitehouse** [pwyf/aid-transparency-tracker#530]
Going to /organisations/publication_index.csv results in the following error message

Error type | SystemError
Error message | <built-in function uwsgi_sendfile> returned a result with an error set

**Comment by Lathrisk** [comment]
A fix has been applied for this issue that converts the StringIO object to a BytesIO object (see PR #531). As well as turning off the uWSGI file wrapper function.
