### ISSUE TITLE
test results API needs to support aggregation types

### ISSUE THREAD

**Issue by shreyabasu** [pwyf/aid-transparency-tracker#92]
See here: http://173.246.104.74/publish/organisations/FI-3/publication/detail/

The math for the test 'Description, more than 40 chars' does not add up. The percentage score says 96% (of 592 files). However there are more than 40 'fail' results.

**Comment by andylolz** [comment]
I guess this must have been fixed – I’m not able to recreate the bug described (looks fine to me) so closing.
